// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPZeDDWokdzK3vq3Of2ww7PcRU79BxCy0',
    appId: '1:740587446040:web:ebf4b79e0b4cf15e3dc86d',
    messagingSenderId: '740587446040',
    projectId: 'nmjpfinal',
    authDomain: 'nmjpfinal.firebaseapp.com',
    storageBucket: 'nmjpfinal.appspot.com',
    measurementId: 'G-FBV1J30BX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvyL1yMhBHDgTU5efD3BDZsSmci8Oiqmc',
    appId: '1:740587446040:android:852f356ef0a642de3dc86d',
    messagingSenderId: '740587446040',
    projectId: 'nmjpfinal',
    storageBucket: 'nmjpfinal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRnuvSi-pG5Aur5NeLZef2bdOBgZSCDJw',
    appId: '1:740587446040:ios:08d16ece3202b7863dc86d',
    messagingSenderId: '740587446040',
    projectId: 'nmjpfinal',
    storageBucket: 'nmjpfinal.appspot.com',
    iosBundleId: 'com.example.nmjpfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRnuvSi-pG5Aur5NeLZef2bdOBgZSCDJw',
    appId: '1:740587446040:ios:08d16ece3202b7863dc86d',
    messagingSenderId: '740587446040',
    projectId: 'nmjpfinal',
    storageBucket: 'nmjpfinal.appspot.com',
    iosBundleId: 'com.example.nmjpfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPZeDDWokdzK3vq3Of2ww7PcRU79BxCy0',
    appId: '1:740587446040:web:505546b9c889ad663dc86d',
    messagingSenderId: '740587446040',
    projectId: 'nmjpfinal',
    authDomain: 'nmjpfinal.firebaseapp.com',
    storageBucket: 'nmjpfinal.appspot.com',
    measurementId: 'G-DX48RCB1SM',
  );
}
